### ISSUE TITLE
Hello, I would like to know if your EDCilrcle can realize real-time circular recognition

### ISSUE THREAD

**Issue by zhangyuqiqiyuzhang** [CihanTopal/ED_Lib#1]
Hello, I would like to know if your EDCilrcle can realize real-time circular recognition

**Comment by CihanTopal** [comment]
Hello Zhang. Execution time depends on the image resolution and number of circular arcs in the image.
Though, we can say that EDCircles runs about 10~20 milliseconds for 1280x720 images in average on an ordinary desktop computer.
You can check timing values in the paper, hovewer, keep in mind that you can get even faster execution with a more recent CPU. 
Paper link: https://www.sciencedirect.com/science/article/pii/S0031320312004268.

**Comment by zhangyuqiqiyuzhang** [comment]
Hello, I tried the following code, connected to the camera, but can't do real-time detection. Have you tried real-time measurement, thank you

**Comment by CihanTopal** [comment]
I tested EDCircles algorithm on a 3.7 GHz CPU and measured ~55 ms for the 1280x960 test image (billiard.jpg) in the repo. That means the algorithm can run upto ~20 fps for HD images. You might be counting drawing/visualization functions beside the actual image processing computation stuff? If so, you should discard them because the actual detection routines happen only in the constructor.
